POST localhost:3000/videos
Content-Type: application/json

{
    "title": "Video teste",
    "description": "Teste de coisa meu irmao",
    "duration": 123
}

###
GET localhost:3000/videos

###
DELETE localhost:3000/videos/

###
PUT localhost:3000/videos/